# app:
#   datasource:
#     driverClassName: com.mysql.jdbc.Driver
#     url: jdbc:mysql://localhost:3606/testdbb
#     username:root
#     password:aa18aa01
#   jpa:
#     hibernate.ddl-auto: update
#     generate-ddl: true
#     show-sql: true